services:
  fastapi:
    build: .
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    networks:
      - app_network
  
  caddy:
    image: caddy:latest
    container_name: caddy_server
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app_network
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      # - caddy_data:/data
      # - caddy_config:/config

networks:
  app_network:

# volumes:
#   caddy_data:
#   caddy_config: